### ISSUE TITLE
Crash: no empty constructor

### ISSUE THREAD

**Issue by khk624** [ConnectSDK/Connect-SDK-Android-API-Sampler#14]
01-19 14:01:54.766: E/AndroidRuntime(15665): FATAL EXCEPTION: main
01-19 14:01:54.766: E/AndroidRuntime(15665): Process: com.connectsdk.sampler, PID: 15665
01-19 14:01:54.766: E/AndroidRuntime(15665): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.connectsdk.sampler/com.connectsdk.sampler.MainActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.connectsdk.sampler.fragments.MediaPlayerFragment: make sure class name exists, is public, and has an empty constructor that is public
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2202)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.os.Looper.loop(Looper.java:136)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at dalvik.system.NativeStart.main(Native Method)
01-19 14:01:54.766: E/AndroidRuntime(15665): Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.connectsdk.sampler.fragments.MediaPlayerFragment: make sure class name exists, is public, and has an empty constructor that is public
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.support.v4.app.Fragment.instantiate(Fragment.java:431)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.support.v4.app.FragmentState.instantiate(Fragment.java:101)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1823)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:264)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:122)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at com.connectsdk.sampler.MainActivity.onCreate(MainActivity.java:117)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.Activity.performCreate(Activity.java:5275)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	... 11 more
01-19 14:01:54.766: E/AndroidRuntime(15665): Caused by: java.lang.InstantiationException: can't instantiate class com.connectsdk.sampler.fragments.MediaPlayerFragment; no empty constructor
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at java.lang.Class.newInstanceImpl(Native Method)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at java.lang.Class.newInstance(Class.java:1208)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	at android.support.v4.app.Fragment.instantiate(Fragment.java:420)
01-19 14:01:54.766: E/AndroidRuntime(15665): 	... 19 more

**Comment by khk624** [comment]
This has been resolved in https://github.com/ConnectSDK/Connect-SDK-Android-API-Sampler/commit/ae3d9dcffa93ccdf84f7e6252fb8567d653eed97
