### ISSUE TITLE
SSDPDiscoveryProvider crashes with StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by softvision-ionutgavris** [ConnectSDK/Connect-SDK-Android-API-Sampler#17]
We see a lot of crashes generated by SSDPDiscoveryProvider from our app that is published on the Google Play store.

java.lang.StringIndexOutOfBoundsException: length=1024; regionStart=0; regionLength=-1
       at java.lang.String.startEndAndLength(String.java:588)
       at java.lang.String.substring(String.java:1475)
       at com.connectsdk.core.upnp.ssdp.SSDP$ParsedDatagram.()
       at com.connectsdk.core.upnp.ssdp.SSDP.convertDatagram()
       at com.connectsdk.discovery.provider.SSDPDiscoveryProvider$4.run()
       at java.lang.Thread.run(Thread.java:841)

We are currently using the 1.3 library version.

Please check and make sure these are fixed in newer library versions and if possible to provide a patch for the 1.3 lib.

PS. While previous lib versions like 1.2.x also generated crashes because of SSDPDiscoveryProvider.sendSearch() Timers, these appear to be fixed in 1.3.

**Comment by softvision-ionutgavris** [comment]
Moved to Connect-SDK-Android-Core
